name: juz_amma_puzzle
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: 3.6.1
  get_it: 4.0.2
  cupertino_icons: ^0.1.2
  reorderables: ^0.3.2
  percent_indicator: ^2.1.3
  curved_navigation_bar: ^0.3.2 #latest version
  shared_preferences: '>=0.5.8 <2.0.0'
  flutter_email_sender: ^3.0.1
  image_picker: ^0.6.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.7.3'

flutter:

  uses-material-design: true

  assets:
    - assets/quran-meta-id.json
    - assets/tanzil/quran-data.xml
    - assets/tanzil/quran-simple.txt
    - assets/tanzil/id.indonesian.txt

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: 'assets/icon/background.png'
  adaptive_icon_foreground: 'assets/icon/foreground.png'
